services:
  api:
    build: .
    restart: unless-stopped
    container_name: api
    command: fastapi run index.py
    ports:
      - 8000:8000
    environment:
      - PYTHONPATH=.
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - 5672

volumes:
  redis_data:
  rabbitmq_data: